# Generated by Django 3.1.5 on 2021-01-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full time job', 'Full time job'), ('Part time job', 'Part time job')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
