# Generated by Django 3.1.5 on 2021-01-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='exprience',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='job_published_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='job_vacancy',
            field=models.IntegerField(default=1),
        ),
    ]
