# Generated by Django 3.1.5 on 2021-01-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210116_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
