# Generated by Django 3.1.5 on 2021-01-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='job.job_category'),
            preserve_default=False,
        ),
    ]
